import { type Article } from '../types/models';

export interface PrintOptions {
  tallyBoxes: 60 | 100;
}

export interface IPrintExportService {
  triggerPrint(article: Article, options: PrintOptions): void;
  generateMarkdown(article: Article, options: PrintOptions): string;
  copyRichTextToClipboard(article: Article, options: PrintOptions): Promise<boolean>;
}

function buildMarkdownGrid(boxCount: number): string {
  const cols = 10;
  const rows = Math.ceil(boxCount / cols);
  let table = '| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 |\n|---|---|---|---|---|---|---|---|---|---|\n';

  for (let r = 0; r < rows; r++) {
    const rowBoxes = Array(cols).fill('[ ]').join(' | ');
    table += `| ${rowBoxes} |\n`;
  }
  return table;
}

export class PrintExportService implements IPrintExportService {
  triggerPrint(_article: Article, _options: PrintOptions): void {
    if (typeof window !== 'undefined') {
      window.print();
    }
  }

  generateMarkdown(article: Article, options: PrintOptions): string {
    const totalReps = options.tallyBoxes === 60 ? 300 : 500;
    const table = buildMarkdownGrid(options.tallyBoxes);

    return [
      `# ${article.title}`,
      `> Target Language: ${article.targetLang} | Current Progress: ${article.currentCount} / ${article.targetCount}`,
      '',
      '## Shadowing Text',
      article.targetText,
      '',
      article.sourceText ? `### Source Reference\n${article.sourceText}\n` : '',
      `## Tally Sheet (${options.tallyBoxes} Boxes / ${totalReps} Total Reps)`,
      table,
      '',
      '> *Generated by TalkDrill - Shadowing & Overlearning Trainer*',
    ].join('\n');
  }

  async copyRichTextToClipboard(article: Article, options: PrintOptions): Promise<boolean> {
    if (typeof navigator === 'undefined' || !navigator.clipboard) {
      return false;
    }

    try {
      const text = this.generateMarkdown(article, options);
      await navigator.clipboard.writeText(text);
      return true;
    } catch {
      return false;
    }
  }
}

export const printExportService = new PrintExportService();
